    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);

    PInteger(pResult)^ := PInteger(pQuad)^;
    b := pResult^.peRed;
    pResult^.peRed := pResult^.peBlue;
    pResult^.peBlue := b;

    inc(pResult);
    inc(pQuad);
