{      pResult^.rgbRed := pEntry^.peRed;
      pResult^.rgbGreen := pEntry^.peGreen;
      pResult^.rgbBlue := pEntry^.peBlue;
      pResult^.rgbReserved := 0;}

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

    PInteger(pResult)^ := PInteger(pEntry)^;
    b := pResult^.rgbRed;
    pResult^.rgbRed := pResult^.rgbBlue;
    pResult^.rgbBlue := b;

    inc(pResult);
    inc(pEntry);

